categories/urls.py
from . import views
from django.urls import path
from django.conf.urls import url

app_name = 'categories'

urlpatterns = [

	path('', views.indexCategories, name='cIndex'),




]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [

	path('', views.indexHome, name='hIndex'),
]

products/urls.py
from . import views
from django.urls import path

app_name = 'products'

urlpatterns = [

    path('<slug:generalItem_slug>/product-id=<int:Product_id>/', views.productPage, name='productPage'),    

    path('productFilter/', views.ajaxProductFilter, name='productFilter'),

    path('table/filterTableAjax/', views.ajaxTable, name='tableDisplay'),
    path('table/UPDATEfilterTableAjax/', views.ajaxTableUpdate, name='tableDisplayUpdate'),
    path('selection/filterSizeAjax/', views.ajaxSizeSelection, name='sizeDisplay'),
    path('map/markersMapAjax/', views.ajaxMarkersMap, name='mapMarker'),


    path('<str:Category_cName>/', views.indexItems, name='productListing'),


    #for trying to update URL wihout refreshing experiments
    path('<str:Category_cName>/<str:serializedForm>', views.indexItems, name='productListingSerialize'),


    
    
    


    
    #removed URL below, saved it for future reference
    #path('<slug:generalItem_slug>/product-id=<int:Product_id>/<slug:selectedStore_slug>/store-id=<int:selectedStoreId>/', views.productPage, name='productPageStoreSelected'),
    #path('sizeSubmit/', views.sizeSubmit, name="sizeSubmit"), (this url was used for ajax form submission)
]

















sale/urls.py
from . import views
from django.urls import path

app_name = 'sale'


urlpatterns = [

    path('<str:SaleCategory_cName>/', views.saleItems, name='saleProductListing'),



    

]






















smplyStack/urls.py
from django.contrib import admin
from django.conf.urls import include, re_path
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from authentication import views as authentication_views
urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('home.urls')),
	path('categories/', include('categories.urls')),
	path('stores/', include('store.urls')),
	path('product/', include('products.urls')),
	path('sale/', include('sale.urls')),
	path('home/', authentication_views.home, name = 'home'),
    path('login/', auth_views.login, {'template_name': 'login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': 'login'}, name='logout'),
    path('signup/', authentication_views.signup, name='signup'),
    path('account_activation_sent/',authentication_views.account_activation_sent, \
    	name='account_activation_sent'),
    path('activate/<uidb64>/<token>',\
    	authentication_views.activate, name='activate'),


	#testing for solr search:
	path('search/', include('haystack.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


app_name = 'store'


urlpatterns = [

	path('map/filterMapAjax/', views.filterMapAjax, name='ajaxMapFilter'),
	path('map/ajaxStoreCheckboxFilter/', views.filterStoreCheckboxAjax, name='ajaxStoreCheckboxFilter'),
	path('map/ajaxMarkerIconGenerate/', views.MarkerIconGenerateAjax, name='ajaxMarkerIconGenerate'),
	path('map/ajaxStoreSearch/', views.StoreSearchAjax, name='StoreSearchAjax'),

	path('list/', views.indexStore, name='sIndex'),
	path('map/', views.indexStoreMap, name='map'),
	path('<slug:store_Slug>/store-id=<int:store_Id>/', views.storePage , name='storePage'),

]

home/models.py
from django.db import models

# Create your models here.

#need to create users storage, with username, password !DJANGO ALREADY HAS ABILITY TO CREATE USERS



#class category(models.Model):
	#dId = models.AutoField(primary_key=True)
#	cName = models.CharField(max_length=200)

	
#class store(models.Model):
	#sId = models.AutoField(primary_key=True)
#	sCategory = models.ForeignKey(category, on_delete=models.CASCADE)
#	sName = models.CharField(max_length=200)
#	sLogo = models.CharField(max_length=1000) #to be changed to actual picture of each store

#class item(models.Model):
#	iCategory = models.ForeignKey(store, on_delete=models.CASCADE)
#	iName = models.CharField(max_length=200)
#	iPicture = models.CharField(max_length=1000) #to be changed to actual picture of each item, different angles
#	iPrice = models.BigIntegerFIeld
	
	





home/views.py
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from django.http import HttpResponse
from categories.models import Category, subCategory



def indexHome(request):




	context = {
		'allCategory': Category.objects.all().order_by('cName')


	}

	return render(request,'homePage/homeIndex.html', context)

templates/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/account_activation_invalid.html
{% extends 'base_authentication.html' %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

templates/account_activation_sent.html
{% extends 'base_authentication.html' %}

{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		{%block cssFiles%} 
		{%endblock%}
		<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>		
		<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		
		<link rel="stylesheet" type="text/css" href="{% static 'home/styleNav.css' %}" />
		
		<title>{%block title%}SMPLFY:Your Local Market{%endblock%}</title>
		
		<nav class="navbar navbar-default cusNav">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="{% url 'home:hIndex' %}"><img id="Logo" src="{% static 'home/images/Logo2.png' %}" alt="SMPLFY"></a>
				</div>
			
				<div class="collapse navbar-collapse" id="topNavBar">
					<ul class="nav navbar-nav cusNav">
						<li>
							<div class="dropdown">
								<a id="dropbtn" href="{% url 'categories:cIndex' %}">CATEGORIES   <i class="fa fa-caret-down"></i></a>
								<div class="dropdown-content">
									{% for categorySelected in allCategory %}
										<a class="categoryDropDown" href="{% url 'products:productListing' categorySelected.cName%}">{{categorySelected.cName}}</a>
									{% endfor %}
								</div>
								
							</div>
						</li>
						<li>
							<a id="button" href="{% url 'store:sIndex' %}">STORES</a>
						</li>
						<li>
							<div class="dropdown">
								<a id="dropbtn" href="#">SALE   <i class="fa fa-caret-down"></i></a>
								<div class="dropdown-content">
									{% for categorySelected in allCategory %}
										<a class="categoryDropDown" href="{% url 'sale:saleProductListing' categorySelected.cName%}">{{categorySelected.cName}}</a>
									{% endfor %}									
								</div>

							</div>

							<!--
							<a id="button" href="#">SALE</a>
							-->

						</li>
						<li>
							<a id="button" href="#">SERVICES</a>
						</li>
						<li>
							<a id="button" href="#">DELIVER</a>
						</li>								
						<li>
							<a id="button" href="#">SELL</a>
						</li>
						<li>
							<a id="button" href="{% url 'login' %}">MY ACCOUNT</a>
						</li>
					</ul>
			
			</div>
		
		</nav>
	</head>
	
	
	<body>
		{% block body %}
		{%endblock%}
		<div class="bottomBanner">
			<div class="bottomBannerContentCtn">


				<div class="bottomBannerColumn col-xs-3 about">
					<h3 class="bottomBannerTitle">About Us</h3>
					<ul class="bottomBannerListing">
						<li><a class="bottomBannerLink" href="#">About SMPLFY</a></li>
						<li><a class="bottomBannerLink" href="#">Our Services</a></li>
						<li><a class="bottomBannerLink" href="#">How it Works</a></li>
					</ul>
				</div>
		
				<div class="bottomBannerColumn col-xs-3 customerService">
					<h3 class="bottomBannerTitle">Customer Service</h3>
					<ul class="bottomBannerListing">
						<li><a class="bottomBannerLink" href="#">Your Account</a></li>
						<li><a class="bottomBannerLink" href="#">Your Purchases</a></li>
						<li><a class="bottomBannerLink" href="#">Delivery</a></li>
						<li><a class="bottomBannerLink" href="#">Help</a></li>
					</ul>
				</div>
			</div>
		</div>

		


	</body>
	
	
</html>
	
	
	
	
	
	
	
	

templates/base_authentication.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}smplyStack Users{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>My Site</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">logout</a>
      {% else %}
        <a href="{% url 'login' %}">login</a> / <a href="{% url 'signup' %}">signup</a>
      {% endif %}
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

templates/home.html
{% extends 'base_authentication.html' %}

{% block content %}
  <h2>Welcome, {{ user.get_full_name }} <small>{{ user.username }}</small>!</h2>
  <p>Your birth date: {{ user.profile.birth_date }}</p>
  <p>Your email: {{ user.email }}</p>
  <p>Your postal code: {{ user.profile.postal_code }}</p>  
{% endblock %}

templates/login.html
{% extends 'base_authentication.html' %}

{% block content %}
  <h2>Log in to My Site</h2>
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <a href="{% url 'signup' %}">New to My Site? Sign up</a>
  </form>
{% endblock %}

templates/signup.html
{% extends 'base_authentication.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}