home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [

	path('', views.indexHome, name='hIndex'),
]

products/urls.py
from . import views
from django.urls import path

app_name = 'products'

urlpatterns = [

    path('<slug:generalItem_slug>/product-id=<int:Product_id>/', views.productPage, name='productPage'),    

    path('productFilter/', views.ajaxProductFilter, name='productFilter'),

    path('table/filterTableAjax/', views.ajaxTable, name='tableDisplay'),
    path('table/UPDATEfilterTableAjax/', views.ajaxTableUpdate, name='tableDisplayUpdate'),
    path('selection/filterSizeAjax/', views.ajaxSizeSelection, name='sizeDisplay'),
    path('map/markersMapAjax/', views.ajaxMarkersMap, name='mapMarker'),


    path('<str:Category_cName>/', views.indexItems, name='productListing'),


    #for trying to update URL wihout refreshing experiments
    path('<str:Category_cName>/<str:serializedForm>', views.indexItems, name='productListingSerialize'),


    
    
    


    
    #removed URL below, saved it for future reference
    #path('<slug:generalItem_slug>/product-id=<int:Product_id>/<slug:selectedStore_slug>/store-id=<int:selectedStoreId>/', views.productPage, name='productPageStoreSelected'),
    #path('sizeSubmit/', views.sizeSubmit, name="sizeSubmit"), (this url was used for ajax form submission)
]

















smplyStack/urls.py
from django.contrib import admin
from django.conf.urls import include, re_path
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from authentication import views as authentication_views
urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('home.urls')),
	path('categories/', include('categories.urls')),
	path('stores/', include('store.urls')),
	path('product/', include('products.urls')),
	path('sale/', include('sale.urls')),
	path('home/', authentication_views.home, name = 'home'),
    path('login/', auth_views.login, {'template_name': 'login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': 'login'}, name='logout'),
    path('signup/', authentication_views.signup, name='signup'),
    path('account_activation_sent/',authentication_views.account_activation_sent, \
    	name='account_activation_sent'),
    path('activate/<uidb64>/<token>',\
    	authentication_views.activate, name='activate'),


	#testing for solr search:
	path('search/', include('haystack.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


app_name = 'store'


urlpatterns = [

	path('map/filterMapAjax/', views.filterMapAjax, name='ajaxMapFilter'),
	path('map/ajaxStoreCheckboxFilter/', views.filterStoreCheckboxAjax, name='ajaxStoreCheckboxFilter'),
	path('map/ajaxMarkerIconGenerate/', views.MarkerIconGenerateAjax, name='ajaxMarkerIconGenerate'),
	path('map/ajaxStoreSearch/', views.StoreSearchAjax, name='StoreSearchAjax'),

	path('list/', views.indexStore, name='sIndex'),
	path('map/', views.indexStoreMap, name='map'),
	path('<slug:store_Slug>/store-id=<int:store_Id>/', views.storePage , name='storePage'),

]

store/models.py
from django.db import models
from django.utils.text import slugify
from categories.models import Category

import json
import urllib.parse
from decimal import Decimal

class City (models.Model):
	city = models.CharField(max_length=100)
	country = models.CharField(max_length=100)
	def __str__(self):
		return str(self.city)

class Store (models.Model):
	sName = models.CharField(max_length=200)
	sCategory = models.ManyToManyField(Category)
	sLogo = models.ImageField(upload_to='storeLogos',blank=True) #need to change, set up photo directory
	slug = models.SlugField(blank=True, max_length=300)

	sLogoURL = models.CharField(max_length=1000, blank=True)

	def __str__(self):
		return str(self.id)+":"+str(self.sName)
	
	def save(self, *args, **kwargs):
		self.slug = slugify(self.sName)
		super(Store,self).save(*args, **kwargs)
	

class StoreLocation (models.Model):
	parentStore =  models.ForeignKey(Store, on_delete=models.CASCADE)
	locationCity =  models.ForeignKey(City, on_delete=models.CASCADE, null=True)
	address = models.CharField (max_length = 300, blank = True)
	postalCode = models.CharField(max_length= 100)
	phoneNum = models.CharField (max_length=20, blank=True, null=True)
	email = models.EmailField(max_length=100, blank=True)
	latitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True )
	longitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True,  null=True)
	
	def __str__(self):
		return "Self: " + str(self.id) + " Parent: " +str(self.parentStore) + " " + str(self.locationCity) + " " + str(self.address) 


	def save(self, *args, **kwargs):
		if not self.latitude or not self.longitude:
			self.latitude, self.longitude = self.geocode(self.address + " " + self.postalCode)
		
		super(StoreLocation, self).save()

	def geocode(self, address):
		address = urllib.parse.quote_plus(address)
		maps_api_url = "?".join([
			"http://maps.googleapis.com/maps/api/geocode/json",
			urllib.parse.urlencode({"address":address, "sensor":False})
		])
		response = urllib.request.urlopen(maps_api_url)
		data = json.loads(response.read().decode('utf8'))

		if data['status'] == 'OK':
			lat = data['results'][0]['geometry']['location']['lat']
			lng = data['results'][0]['geometry']['location']['lng']
			return Decimal(lat), Decimal(lng)

store/views.py
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from django.http import HttpResponse
from categories.models import Category, subCategory
from products.models import Product, StoreInventory
from .models import Store, StoreLocation, City
from functions.commonFunctions import loopCalculator

from django.db.models import Avg, Count




def storePage(request, store_Slug, store_Id):
	noResult = False
	saveFilter = False


	selectedStore = Store.objects.get(pk=store_Id)
	storeDepartments = selectedStore.sCategory.all()
	storeLocations = StoreLocation.objects.all().filter(parentStore_id = store_Id)

	qStoreInventory = StoreInventory.objects.filter(storeLocation__parentStore=store_Id)
	productIds = qStoreInventory.values_list('product', flat=True).distinct()
	
	qFootwear = Product.objects.filter(pk__in=set(productIds)).distinct().order_by('generalItem__shoeName', 'additionalName')

	numOfCol = 4
	numOfRow = loopCalculator(len(qFootwear), numOfCol)

	if(request.GET.get('filterBtn')):
		if (request.GET.getlist('storeLoc')!=[]):
			storeLocIDs = request.GET.getlist('storeLoc')
			availableInventory = StoreInventory.objects.filter(storeLocation__in=storeLocIDs)
			productIDs = availableInventory.values_list('product', flat=True).distinct()
			qFootwear = qFootwear.filter(id__in=productIDs)
			saveFilter= True

	if (not qFootwear):
		noResult = True

	qFootwear = qFootwear.distinct()
	


	#Filter out footwear that have no stock available
	qFootwear = qFootwear.annotate(numOfInv=Count('storeinventory'))
	qFootwear = qFootwear.filter(numOfInv__gte=1)

	#Add average cost as object onto each qs entry
	qFootwear = qFootwear.annotate(avgCost=Avg('storeinventory__regularPrice'))


	context = {
		'allCategory': Category.objects.all().order_by('cName'),
		'selectedStore': selectedStore,
		'storeDepartments': storeDepartments,
		'storeLocations': storeLocations,
		'qStoreInventory': qStoreInventory,
		'qFootwear': qFootwear, 

		'amountOfProducts': len(qFootwear),
		'numOfRow': range(int(numOfRow+1)),
		'numOfColRange': range(int(numOfCol)),
		'numOfCol': numOfCol,

		'saveFilter': saveFilter,
		'noResult': noResult,


	}
	return render(request, 'store/storePage.html', context) 

#For store listing page--------------------------------------------------------
def indexStore(request):
	saveFilter = False

	allCategory = Category.objects.all().order_by('cName')
	error = False
	noResults = False

	qStores = Store.objects.all()
	q = "Search Store..."	


	if(request.GET.get('searchBtn')):
		q = request.GET['q'] 
		if q:
			qStores = qStores.filter(sName__icontains=q).order_by("sName").distinct()
		else:
			q = "Search Store..."
			error = True
		saveFilter = False
			

	if(request.GET.get('filterBtn')):
		categoryInput = request.GET.getlist('categoryName')


		if(categoryInput):
			qStores = qStores.filter(sCategory__in=categoryInput).order_by("sName").distinct()
		saveFilter = True

	if (not qStores):
		noResults = True
		
	context = {
		'Categories': Category.objects.all(),
		'SearchTxt': q,
		'qStores': qStores,
		'error': error,
		'noResults': noResults,
		'allCategory': allCategory,
		'saveFilter': saveFilter,
	}
	return render(request, 'store/storeIndex.html', context)

# these imports are used exclusively for functions below
from django.http import JsonResponse
import json
import math

from django.conf import settings

def filterMapAjax (request):
	seeAll = request.GET.get('seeAll')
	qStoreLocation = StoreLocation.objects.all().order_by('id')
	allStore = Store.objects.all()
	qStoreListing = StoreLocation.objects.all().order_by('id')

	if (seeAll == 'false'):
		checkedRadioID = request.GET.getlist('checkedRadioID[]')
		checkedCategoryID = request.GET.getlist('checkedCategoryID[]')
		checkedStoreID = request.GET.getlist('checkedStoreID[]')

		if checkedRadioID != []:
			qStoreLocation = qStoreLocation.filter(locationCity__in=checkedRadioID)
			qStoreListing = qStoreListing.filter(locationCity__id__in=checkedRadioID) #for store filtering
		if checkedCategoryID != []:
			qStoreLocation = qStoreLocation.filter(parentStore__sCategory__in=checkedCategoryID)
			qStoreListing = qStoreListing.filter(parentStore__sCategory__in=checkedCategoryID) #for store filtering
		if checkedStoreID != []:
			qStoreLocation = qStoreLocation.filter(parentStore__id__in=checkedStoreID)

		#Calculate User Distance---------------
		distanceFilterVal = request.GET.get('distanceValue')
		if (distanceFilterVal != "all"):
			userLat = float(request.GET.get('userLat'))
			userLng = float(request.GET.get('userLng'))
			if (distanceFilterVal == "10"):
				distance = 10
			elif (distanceFilterVal == "25"):
				distance = 25
			elif(distanceFilterVal=="50"):
				distance = 50
			elif(distanceFilterVal=="100"):
				distance = 100

			latBounds = distance/110.574
			lngBounds = distance/(111.320*(math.cos(math.radians(userLat))))

			latUpperBounds = userLat + latBounds
			latLowerBounds = userLat - latBounds	
			lngUpperBounds = userLng + lngBounds
			lngLowerBounds = userLng - lngBounds

			qStoreLocation = qStoreLocation.filter(latitude__gte=latLowerBounds, latitude__lte=latUpperBounds)
			qStoreLocation = qStoreLocation.filter(longitude__gte=lngLowerBounds, longitude__lte= lngUpperBounds)
			
			qStoreListing = qStoreListing.filter(latitude__gte=latLowerBounds, latitude__lte=latUpperBounds)
			qStoreListing = qStoreListing.filter(longitude__gte=lngLowerBounds, longitude__lte= lngUpperBounds)
		#--------------------------------------

		#Used later for refreshing store filter section
		qStoreIDs = qStoreListing.values_list('parentStore_id', flat=True).order_by().distinct()

	else:	
		#Used later for refreshing store filter section
		qStoreIDs = qStoreLocation.values_list('parentStore_id', flat=True).order_by().distinct()

	qStoreNames = qStoreLocation.values_list('parentStore__sName', flat=True)
	qPhoneNum = qStoreLocation.values_list('phoneNum', flat=True)
	qStoreSlugs = qStoreLocation.values_list('parentStore__slug', flat=True)
	qStorePics = qStoreLocation.values_list('parentStore__sLogo', flat=True)
	qStoreIDsForInfoBox = qStoreLocation.values_list('parentStore__id', flat=True)


	qStorePicsToLoc = []
	for i in qStorePics:
		qStorePicsToLoc = qStorePicsToLoc + [settings.MEDIA_URL + i]
	
	qStoreNames = list(qStoreNames)
	qPhoneNum = list(qPhoneNum)
	qStoreSlugs = list(qStoreSlugs)
	qStoreIDs = list(qStoreIDs)
	qStoreIDsForInfoBox = list(qStoreIDsForInfoBox)

	data = {
		'qStoreLocation': list(qStoreLocation.values()),  
		'qStoreIDs': qStoreIDs, 
		'allStore': list(allStore.values()),  
		'qStorePicsToLoc':qStorePicsToLoc,
		'qStoreNames': qStoreNames,
		'qPhoneNum':qPhoneNum,
		'qStoreSlugs': qStoreSlugs,
		'qStoreIDsForInfoBox':qStoreIDsForInfoBox,
	}
	return JsonResponse(data)


def filterStoreCheckboxAjax (request): #update filter boxes in store checkbox filter section

	qStoreIDs = request.GET.getlist('qStoreIDs[]')
	qStoreIDsIntList = []
	
	for i in range(len(qStoreIDs)):
		qStoreIDsIntList = qStoreIDsIntList + [int(qStoreIDs[i])] 

	if len(qStoreIDsIntList) != 0:
		qStores = Store.objects.filter(id__in=qStoreIDsIntList).order_by('sName')
	else:
		qStores = "None"

	context = {
		'qStores': qStores,
		'qStoreIDsIntList':qStoreIDsIntList
	}
	return render(request, 'store/ajaxTemplates/storeCheckboxSelection.html', context)


def MarkerIconGenerateAjax(request): # generate marker icons
	qStoreLocID = request.GET.get('storeLocID')
	storeLoc = StoreLocation.objects.filter(id=qStoreLocID)
	parentStorePic = storeLoc.values_list('parentStore_sLogo', flat=True).distinct()
	context = {
		'parentStorePic': parentStorePic
	}
	return JsonResponse(context)


#------------Store Search in Map Page------------------------------------------
def StoreSearchAjax(request):

	qStoreLocation = StoreLocation.objects.all().order_by('id')

	#Get Filter Lists
	checkedRadioID = request.GET.getlist('checkedRadioID[]')
	checkedCategoryID = request.GET.getlist('checkedCategoryID[]')

	#Filter by filter city, category, store lists--------------------
	if checkedRadioID !=[]:
		qStoreLocation = qStoreLocation.filter(locationCity__id__in=checkedRadioID)
	if checkedCategoryID !=[]:
		qStoreLocation = qStoreLocation.filter(locationCity__id__in=checkedCategoryID)

	#Calculate User Distance---------------
	distanceFilterVal = request.GET.get('distanceValue')
	if (distanceFilterVal != "all"):
		userLat = float(request.GET.get('userLat'))
		userLng = float(request.GET.get('userLng'))
		if (distanceFilterVal == "10"):
			distance = 10
		elif (distanceFilterVal == "25"):
			distance = 25
		elif(distanceFilterVal=="50"):
			distance = 50
		elif(distanceFilterVal=="100"):
			distance = 100

		latBounds = distance/110.574
		lngBounds = distance/(111.320*(math.cos(math.radians(userLat))))

		latUpperBounds = userLat + latBounds
		latLowerBounds = userLat - latBounds	
		lngUpperBounds = userLng + lngBounds
		lngLowerBounds = userLng - lngBounds
		qStoreLocation = qStoreLocation.filter(latitude__gte=latLowerBounds, latitude__lte=latUpperBounds)
		qStoreLocation = qStoreLocation.filter(longitude__gte=lngLowerBounds, longitude__lte= lngUpperBounds)
	#--------------------------------------

	#Get search value
	searchValue = request.GET.get('searchValue')
	if (searchValue): #if search is not empty
		searchedStores = Store.objects.filter(sName__icontains=searchValue) #search for stores that contain search term
		searchedStoresIDs = searchedStores.values_list('id', flat=True) #generate list of Ids of stores containing search term
		storeSearch = qStoreLocation.filter(parentStore__id__in=searchedStoresIDs) #filter for the general stores that meet the search and filter criteria

templates/store/storeIndex.html
{% extends 'base.html' %}
{% load static %}
{% load customTemplateStores %}

<html>
	<head>
		{% block cssFiles%}
			<script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
			<link rel="stylesheet" type="text/css" href="{% static 'store/styleStore.css' %}" />
		{% endblock %}
		<title>{% block title %} SMPLY: Stores {% endblock %}</title>
	
	
	</head>

	{% block body %}
	<body onload="reset('{{saveFilter}}')">
		<div class="line">
			<a class="link" href="{% url 'store:map' %}">Map of Marketplace </a>
			<h1 class="title">Stores</h1>
		
		</div>
		<div class="layout">
			<div class="sideBar">
				<form method="get">
					<input id="search_box" type="text" name="q" placeholder='{{SearchTxt}}'>
					<input class="button" id="search_submit" type="submit" name="searchBtn" value="Search"> 
					
				</form>

				<form method="GET">
					<input id="seeAll" type="submit" class="button" name="allStoresBtn" value="All Stores">
					
				</form>

				<br>
				{% if error %}
					<h5 class="errorMsg">No Search Entered</h5>
				{% endif %}

				<form method="GET" class="filterSec">
					<h4 class="header">Filter Stores by Category:</h4>
					<div id="checkbox-container">
						{% for SelectedCategory in Categories %}
							<input  onchange="submitFunc()" type="checkbox" id="{{SelectedCategory.id}}" name="categoryName" value="{{SelectedCategory.id}}">
							<label for="{{SelectedCategory.id}}" style="font-family: 'Quicksand', sans-seriff; text-transform: capitalize; ">{{SelectedCategory.cName}}</label>
							<br>
						{% endfor %}
					</div>
					<input id="submitBtn" style="display:none" type="submit" class="button" value="Filter" name="filterBtn">

				</form>
				

			</div>
			
			<div class="display" id="displayContainer">
				{% if noResults %}
					<h3 class="NoStoreFoundMsg">No Stores Found</h3>
				{% endif %}
				
				{% for selectedStore in qStores%}
					<div class="col-sm-2" >
						<div class="content">
							<a class="storeLink"  href="{% url 'store:storePage' store_Slug=selectedStore.slug store_Id=selectedStore.id %}">
								{{selectedStore.sName}}
							</a>
						</div>
					</div>
				{% endfor %}

			</div>
			
		</div>


		<script>
			var checkboxValues = JSON.parse(localStorage.getItem('checkboxValues')) || {};
			var $checkboxes = $("#checkbox-container :checkbox");


			$checkboxes.on("change", function(){
				$checkboxes.each(function(){
					checkboxValues[this.id] = this.checked;
				});
				
				localStorage.setItem("checkboxValues", JSON.stringify(checkboxValues));

			});

			$.each(checkboxValues, function(key, value) {
 
  				$("#" + key).prop('checked', value);
			});
			
			function reset(saveFilter){
				if(saveFilter == "False"){
					$checkboxes.each(function(){
		 				checkboxValues[this.id] = false;
					});
				}
				localStorage.setItem("checkboxValues", JSON.stringify(checkboxValues));
				$.each(checkboxValues, function(key, value){
					$("#" + key).prop('checked', value);
				});
			}
		
			function submitFunc(){
				document.getElementById("submitBtn").click();
			}

			// idk if this section is necessarily needed
			$.ajax({
				url: 'storeIndex.html',
				success: function(data){
					$('#displayContainer').html(data);
				}
			});
			//----------------------------------------------
		</script>
	
	</body>
	{% endblock %}



</html>

templates/store/storePage.html
{% extends 'base.html' %}
{% load static %}
{% load customTemplateFootwear %}

<html>
    <head>
        {% block cssFiles %}
            <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

            <link rel="stylesheet" type="text/css" href="{% static 'store/styleStorePage.css' %}"/>
            <link rel="stylesheet" type="text/css" href="{% static 'store/styleStore.css' %}" />
            <link rel="stylesheet" type="text/css" href="{% static 'items/styleItems.css' %}" />
        {% endblock %}

        {% block title %} SMPLY: {{selectedStore.sName}} {% endblock %}

    </head>

{% block body %}
    <body onload="reset('{{saveFilter}}')"> 
        <div class="line">
            <h1 class="title">{{selectedStore.sName}}</h1>
        </div>        

        <div class="layout">

            <div class="sideBar">
                <form>
                    <input id="search_box" type="text" name="q" placeholder='Search {{selectedStore.sName}}...'>
                    <input class="button" id="search_submit" type="submit" name="searchBtn" value="Search"> Submit 
                </form>
                <form>
                    <input id="seeAll" type="submit" class="button" name="allStoresBtn" value="All Footwear">	
                </form>  

                <div class="selectBoxContainer">
                    <h4 class="header">Filter by Department: </h4>
                    <form>    
                        <select class="selectBox" onchange="submitFuncSelection()" >
                            <option class="option">See All</option>
                            {% for selectedDepartment in storeDepartments %}
                                <option class="option">{{selectedDepartment.cName}}</option>
                            {% endfor %}
                        </select>
                        <input id="submitSelBtn" type="submit" class="button" style="display:none" name="selectionBtn">
                    </form>
                </div>
                
                    <div class="storeLocationFilter">
                        <h4 class="header">Filter by Store Location: </h4>
                        <br><br>
                        <form method="GET" class="filterSec" id="checkbox-form">
                            {% for selectedStoreLocations in storeLocations %}
                                <input type="checkbox" onclick="submitFuncFilterBox()" id="storeLoc_{{selectedStoreLocations.id}}" name="storeLoc" value="{{selectedStoreLocations.id}}">
                                <label for="storeLoc_{{selectedStoreLocations.id}}" style="font-family: 'Quicksand', sans-seriff; text-transform: capitalize;">
                                    {{selectedStoreLocations.locationCity}}: {{selectedStoreLocations.address}}
                                </label> 
                                <br>
                            {% endfor %}
                            <input id="checkBoxFilterBtn" style="display:none" type="submit" class="button" value="Filter" name="filterBtn">
                        </form>
                    </div>
            </div>

            <div class="display">
                {% if noResult %}
                    <h3 class="NoStoreFoundMsg">No Footwear Found</h3>
                {% endif %}

                {% for row in numOfRow %}
                    <div id="productRow">
                    {% with startIndex=row|mul:numOfCol %}
                    {% for col in numOfColRange%}
    
                        {% with productIndex=startIndex|adder:col %}    
                        {% if amountOfProducts > productIndex%}
                                
                            {% with selectedProduct=qFootwear|index:productIndex %}

                            <div class="col-xs-3 productListingBox">
                                <div class="content">
                                    {% if selectedProduct.avgCost %}
                                        <h6 class="avgPrice"> Average Price: ${{selectedProduct.avgCost|floatformat:2}}</h6>
                                    {% else %}
                                        <h6 class="avgPrice">No Stock</h6>
                                    {% endif %}
                                    <a class="productLink" href="{% url 'products:productPage' generalItem_slug=selectedProduct.slug Product_id=selectedProduct.id %}">
                                        <img class="displayPic" alt="{{selectedProduct}}" src="{{selectedProduct.displayPic.url}}">
                                        <h4 class="productTitle">{{selectedProduct.generalItem.shoeName}} {{selectProduct.additionalName}} </h4>
                                        {% if selectedProduct.additionalName != None %}
                                            <h5 class="productTitle" style="display:inline">"{{selectedProduct.additionalName}}"</h5>
                                        {% endif %}
                                    </a>
                                    <h6 class="productDescription">{{selectedProduct.generalItem.brand}}</h6>
                                    <h6 class="productDescription">{{selectedProduct.generalItem.gender}}</h6>
                                    <h6 class="productDescription">{{selectedProduct.generalItem.style}}</h6>
                                        
                                </div>
                            </div>

                            {% endwith %}
    
                        {% endif %}
                        {% endwith %}
    
                    {% endfor %}
                    {% endwith %}
                    </div>

                {% endfor %}
            </div>

        </div>


        <script>
            //var checkboxValuesStoreLoc = JSON.parse(localStorage.getItem('checkboxValuesStoreLoc')) || {};            
            var $checkboxesStoreLoc = $("#checkbox-form :checkbox");
    
            function reset(saveFilter){

                //if(saveFilter == "False"){
                //    $checkboxesStoreLoc.each(function(){
                //        checkboxValuesStoreLoc[this.id] = false;
                //    });
                //}
                var pageURL = window.location.href;
                
                var submittedFormURL = pageURL.split("?")[1];
                
                var splitURLList = submittedFormURL.split("&")
                var loopLength = splitURLList.length-1;

                

                for (var i = 0; i < loopLength; i++){
                    var storeLocOne = splitURLList[i].split("=")[0];
                    var storeLocTwo = splitURLList[i].split("=")[1];
                    var storeLocID = storeLocOne + "_" + storeLocTwo;
                    document.getElementById(storeLocID).checked = true;
                }

                //localStorage.setItem("checkboxValuesStoreLoc", JSON.stringify(checkboxValuesStoreLoc));
                
                //$.each(checkboxValuesStoreLoc, function (key, value){
                //    document.getElementById(key).checked = value;
                //});
            }

            $checkboxesStoreLoc.on("change", function(){
                document.getElementById("checkBoxFilterBtn").click();
                //$checkboxesStoreLoc.each(function(){
                //    checkboxValuesStoreLoc[this.id] = this.checked;
                //});
                //localStorage.setItem("checkboxValuesStoreLoc", JSON.stringify(checkboxValuesStoreLoc));
                //submitFilterForm();
            });

            /*
            function submitFilterForm(){
                document.getElementById("checkBoxFilterBtn").click();
            }
            */

        </script>    
    </body>
{% endblock %}
</html>










